### ISSUE TITLE
3.18 support

### ISSUE THREAD

**Issue by SuperPichu** [timbertson/shellshape#163]
Just updated for 3.18 support and shellshape isn't activating. It loads and I can see the indicator but it doesn't actually tile anything.

**Comment by ElectricPrism** [comment]
This also affects me, I would like to get 3.18 support thank you :)

**Comment by psykotik1** [comment]
me three

**Comment by cpaulik** [comment]
:+1:

**Comment by altercation** [comment]
Under 3.18 spawning a new terminal in floating mode results in a floating terminal as expected. Switching to a tiled mode and spawning a terminal results in a floating terminal resized to the apparent minimum window size possible. No actual tiling occurs.

**Comment by Lucasvo1** [comment]
Having the same issues

**Comment by motdef** [comment]
Same issue with the size of new windows, but tiling is working for me. The padding options are seemingly ignored, though

**Comment by DoctorJellyface** [comment]
The padding options between windows are ignored, but I tiling works after you put the window into tiling mode with `Super+T`.

**Comment by timbertson** [comment]
Padding between tiles seems to be an issue everywhere (#152)

**Comment by person666** [comment]
most of it seems to be broken on 3.18

**Comment by victordiaz** [comment]
I love your extension, I havent moved to 3.18 yet because of it! :D

**Comment by ikhthiandor** [comment]
What broke it for 3.18? Can we please debug the issue together? Shellshape plays an important role in my workflow.

**Comment by timbertson** [comment]
Sorry guys. I should really get 3.18 installed for myself and figure out what's wrong, I've just been quite busy and upgrading my OS isn't as exciting as it used to be ;). If you do have any errors or hunches please feel free to discuss them here, in the meantime I'll try and find some time to fire it up in a VM or something.

**Comment by alefa** [comment]
I seem to have the same issues (windows only get tiled after pressing win+t, new windows are tiny), although I'm running Gnome 3.14 on Debian Jessie. Installed Shellshape from the extensions website. Maybe whatever is causing the issue is not specific to 3.18 after all?

**Comment by ikhthiandor** [comment]
@timbertson is running "r" for restart via Alt+F2 exactly equivalent to gnome-shell --replace?

**Comment by timbertson** [comment]
@ikhthiandor Generally, yes. The only exception is that Alt-f2 method will keep the same environment variables, while `gnome-shell --replace` will use your shell's environment. If you haven't messed with XDG_DATA_DIRS` then this won't matter.

**Comment by timbertson** [comment]
I've finally got 3.18 running in a VM. I'm not sure what to say, but it definitely works for me (and this is a fresh install).

I have fixed a number of bugs today, some of which may be causing weird startup behaviour. I've submitted a new version on extensions.gnome.org. I'll comment here when that's available, please open specific issues if something still isn't working after the next update.

**Comment by timbertson** [comment]
The new version is now up on https://extensions.gnome.org/extension/294/shellshape/

**Comment by ikhthiandor** [comment]
I can confirm what @alefa has said. 
1. The extension works but first you have to tile the window with Super + T first.
2. If you open a new window it's super tiny.

I am ok with (1) but (2) is problematic.

**Comment by alefa** [comment]
@timbertson: Thanks, I tested the new version. Unfortunately, I still have the same problems, so I'll open a new issue.
